### ISSUE TITLE
You got me xD

### ISSUE THREAD

**Issue by CutyCat2000** [mahtoid/mahtoid.github.io#2]
I have a good idea:
If someone opens the website, make it autoplay the video :)

**Comment by mahtoid** [comment]
It should [auto-play by default](https://mahtoid.github/io/rr.mp4), however the file is so large - it's probably the best quality RR you're going to get - that it takes so long to load and render. 

Glad to see it got another one. It used to be where I redirected people on one of my funky links, now people just seem to snoop around and get RR'd by accident 🤷 

Thank you for being honest and surrendering to the RR 💜
